### ISSUE TITLE
the format of this looks wierd

### ISSUE THREAD

**Issue by zachsmith1** [calebjsmith7/randomCat#2]
https://github.com/calebjsmith7/randomCat/blob/2d018ba7085ab06f67b90870161d0bbe643d7118/src/App.js#L6-L39

Did you format your code before submitting a PR? Some of the code looks weird. For example, the class name is on two lines. Try to be clean with your code to make it more easily readable for your peers

**Comment by calebjsmith7** [comment]
fixed formatting issues- thanks!
