### ISSUE TITLE
dynamic image sizing

### ISSUE THREAD

**Issue by zachsmith1** [calebjsmith7/randomCat#3]
https://github.com/calebjsmith7/randomCat/blob/2d018ba7085ab06f67b90870161d0bbe643d7118/src/App.js#L26-L34

Let's say that we wanted the size of the image to be X at all times, unless a user pulled the image up on their phone. How can we add the ability to dynamically adjust the size of the image. 

Use-case 1: On my desktop, each time I refresh I get a different cat image but they are all difference sizes. Lets add a feature that makes all the images the same size (scale up and scale down as needed). 

Use-case 2: Same thing as use-case 1, but how does it work on mobile?

**Comment by calebjsmith7** [comment]
see new update, added dynamic image scaling, thanks!
